-- Generate SQL for duplicating tables
USE ROLE SYSADMIN;
USE DATABASE trustbankdata;

USE WAREHOUSE trustbank_etl_warehouse;

// Ensuring primary and unique constraints are properly set before adding foreign keys
// CUSTOMER_LOOKUP 
ALTER TABLE TRUSTBANKDATA.HARMONIZED.CUSTOMER_LOOKUP
ADD CONSTRAINT pk_cardholderid PRIMARY KEY (CARDHOLDERID);

// ATM_LOOKUP
ALTER TABLE TRUSTBANKDATA.HARMONIZED.ATM_LOOKUP
ADD CONSTRAINT pk_locationid PRIMARY KEY (LOCATIONID);

ALTER TABLE TRUSTBANKDATA.HARMONIZED.CUSTOMER_LOOKUP
ADD CONSTRAINT fk_atmid FOREIGN KEY (ATMID) 
REFERENCES HARMONIZED.ATM_LOOKUP(LOCATIONID);

// BRANCH_LOOKUP 
ALTER TABLE TRUSTBANKDATA.HARMONIZED.BRANCH_LOOKUP
ADD CONSTRAINT pk_branchid PRIMARY KEY (BRANCH_ID);

ALTER TABLE TRUSTBANKDATA.HARMONIZED.CUSTOMER_LOOKUP
ADD CONSTRAINT fk_branchid FOREIGN KEY (BRANCH_ID) 
REFERENCES HARMONIZED.BRANCH_LOOKUP(BRANCH_ID);

// CUSTOMER_DEMO
ALTER TABLE TRUSTBANKDATA.HARMONIZED.CUSTOMER_DEMO
ADD CONSTRAINT pk_cardholderid PRIMARY KEY (CARDHOLDERID);

// LOANS 
ALTER TABLE TRUSTBANKDATA.HARMONIZED.LOAN
ADD CONSTRAINT pk_cardholderid_loanid PRIMARY KEY (CARDHOLDERID, LOAN_ID);
ALTER TABLE TRUSTBANKDATA.HARMONIZED.LOAN
ADD CONSTRAINT fk_cust_lookup FOREIGN KEY (CARDHOLDERID) 
REFERENCES HARMONIZED.CUSTOMER_LOOKUP(CARDHOLDERID);

// BRANCH_PERFORMANCE 
ALTER TABLE TRUSTBANKDATA.HARMONIZED.BRANCH_PERFORMANCE 
ADD CONSTRAINT pk_branchid_date PRIMARY KEY (BRANCH_ID, DATES);
ALTER TABLE TRUSTBANKDATA.HARMONIZED.BRANCH_PERFORMANCE 
ADD CONSTRAINT fk_branchid FOREIGN KEY (BRANCH_ID)
REFERENCES HARMONIZED.BRANCH_LOOKUP (BRANCH_ID);

// INVESTMENTS 
ALTER TABLE TRUSTBANKDATA.HARMONIZED.INVESTMENTS 
ADD CONSTRAINT pk_investmentid_customerid PRIMARY KEY (INVESTMENTID, CUSTOMERID);
ALTER TABLE TRUSTBANKDATA.HARMONIZED.INVESTMENTS 
ADD CONSTRAINT fk_cust_lookup FOREIGN KEY (CUSTOMERID) 
REFERENCES HARMONIZED.CUSTOMER_LOOKUP(CARDHOLDERID);

// TRANSACTIONS and TRANSACTION_TYPE_LOOKUP
ALTER TABLE TRUSTBANKDATA.HARMONIZED.TRANSACTIONS_TYPE_LOOKUP
ADD CONSTRAINT pk_transactiontypeid PRIMARY KEY (TRANSACTIONTYPEID);

ALTER TABLE TRUSTBANKDATA.HARMONIZED.TRANSACTIONS
ADD CONSTRAINT pk_transactionid PRIMARY KEY (TRANSACTIONID);
ALTER TABLE TRUSTBANKDATA.HARMONIZED.TRANSACTIONS
ADD CONSTRAINT fk_transactiontypeid FOREIGN KEY (TRANSACTIONTYPEID) 
REFERENCES HARMONIZED.TRANSACTIONS_TYPE_LOOKUP(TRANSACTIONTYPEID);

// Describing tables to verify structures
DESCRIBE TABLE TRUSTBANKDATA.HARMONIZED.branch_lookup;
DESCRIBE TABLE TRUSTBANKDATA.HARMONIZED.transactions;
