-- Streams

CREATE OR REPLACE STREAM trustbankdata_harmonized_transactions_stream
  ON TABLE TRUSTBANKDATA.HARMONIZED.TRANSACTIONS;

CREATE OR REPLACE STREAM trustbankdata_harmonized_investments_stream
  ON TABLE TRUSTBANKDATA.HARMONIZED.INVESTMENTS;

CREATE OR REPLACE STREAM trustbankdata_harmonized_loan_stream
  ON TABLE TRUSTBANKDATA.HARMONIZED.LOAN;


-- CSD CODE 
-- Replace <schema_name> with 'HARMONIZED' if that's your schema
CREATE OR REPLACE STREAM ATM_LOOKUP_STREAM ON TABLE HARMONIZED.ATM_LOOKUP;
CREATE OR REPLACE STREAM BRANCH_STREAM ON TABLE HARMONIZED.BRANCH;
CREATE OR REPLACE STREAM HOUR_LOOKUP_STREAM ON TABLE HARMONIZED.HOUR_LOOKUP;
CREATE OR REPLACE STREAM VW_INVESTMENT_SUMMARY_STREAM ON TABLE HARMONIZED.VW_INVESTMENT_SUMMARY;
CREATE OR REPLACE STREAM VW_LOAN_ANALYSIS_STREAM ON TABLE HARMONIZED.VW_LOAN_ANALYSIS;
CREATE OR REPLACE STREAM VW_TRANSACTION_SUMMARY_STREAM ON TABLE HARMONIZED.VW_TRANSACTION_SUMMARY;
CREATE OR REPLACE STREAM BRANCH_LOOKUP_STREAM ON TABLE HARMONIZED.BRANCH_LOOKUP;
CREATE OR REPLACE STREAM CUSTOMER_LOOKUP_STREAM ON TABLE HARMONIZED.CUSTOMER_LOOKUP;
CREATE OR REPLACE STREAM SYSTEM_HEALTH_LOGS_STREAM ON TABLE HARMONIZED.SYSTEM_HEALTH_LOGS;
CREATE OR REPLACE STREAM TRANSACTIONS_STREAM ON TABLE HARMONIZED.TRANSACTIONS;
CREATE OR REPLACE STREAM LOAN_STREAM ON TABLE HARMONIZED.LOAN;
CREATE OR REPLACE STREAM V_CUSTOMER_TRANSACTIONS_SUMMARY_STREAM ON TABLE HARMONIZED.V_CUSTOMER_TRANSACTIONS_SUMMARY;
CREATE OR REPLACE STREAM BRANCH_PERFORMANCE_STREAM ON TABLE HARMONIZED.BRANCH_PERFORMANCE;
CREATE OR REPLACE STREAM INVESTMENTS_STREAM ON TABLE HARMONIZED.INVESTMENTS;
CREATE OR REPLACE STREAM TRANSACTIONS_TYPE_LOOKUP_STREAM ON TABLE HARMONIZED.TRANSACTIONS_TYPE_LOOKUP;
CREATE OR REPLACE STREAM VW_BRANCH_PERFORMANCE_STREAM ON TABLE HARMONIZED.VW_BRANCH_PERFORMANCE;
CREATE OR REPLACE STREAM VW_SCHEMA_CHANGE_LOG_STREAM ON TABLE HARMONIZED.VW_SCHEMA_CHANGE_LOG;
CREATE OR REPLACE STREAM VW_TABLE_ACCESS_STATS_STREAM ON TABLE HARMONIZED.VW_TABLE_ACCESS_STATS;
CREATE OR REPLACE STREAM CALENDER_LOOKUP_STREAM ON TABLE HARMONIZED.CALENDER_LOOKUP;
CREATE OR REPLACE STREAM CUSTOMER_DEMO_STREAM ON TABLE HARMONIZED.CUSTOMER_DEMO;
